application:
  port: 6666
  log: 
    path: /home/lingga/Downloads/log/app.log
    maxSize: 1
    maxBackup: 10 # MB
    maxAge: 30 # Days
    compress: true # Disabled by default
  key:
    default: tgcEOnliPuyvSAlOyC84SZu0yeZrfXW8
    rsa:
      public: "-----BEGIN PUBLIC KEY-----\nMIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQCfJ75JadN0Pa/72piFxsVaOmNQ\nXNFsg6wP2ucJ9/Y5xJEV8wWkxbF+DQprXGWAYMXqMq3+xjPQ1++syM+kB8P/T1+Z\nHED0R4r7K6fFsvNpPdN7bc91z/eHxih8UnFXz8GxO8GDqQ4+pSKFAh2kuKMOM4tC\n+qBSLD7BKNPOLGIr6QIDAQAB\n-----END PUBLIC KEY-----\n"
      private: "-----BEGIN RSA PRIVATE KEY-----\nMIICXQIBAAKBgQCfJ75JadN0Pa/72piFxsVaOmNQXNFsg6wP2ucJ9/Y5xJEV8wWk\nxbF+DQprXGWAYMXqMq3+xjPQ1++syM+kB8P/T1+ZHED0R4r7K6fFsvNpPdN7bc91\nz/eHxih8UnFXz8GxO8GDqQ4+pSKFAh2kuKMOM4tC+qBSLD7BKNPOLGIr6QIDAQAB\nAoGAATO8pTNObI9Wt/FDu6bvsKnGPEInNsmb0BbYLeQYkQEiE2ddgIwZthkFHiB5\nh8mzVPyDAeyfUZF/9u8hWlzQpyb2LOSgHraueL7P2jwTQOoE9d4O/7FsXoQB57H6\nl5Dtuoni9O9B/45S6hbUx53Rl2g7RuQj8IGBZccK6IdtU30CQQDRmM/raih6klAd\n2iSu3hBkw/SCr40iCfNHRD21xCNeBdhKddu9Wxaob7XO9ZSZkDrpLDOSlBtMNfZz\n21H3ZnCTAkEAwmQUzQSmJlikLxw3CHxFDeCF39Do+m/wW4GeWUux2QQCg+qFKMLE\nhgXcQr1LSV/EYlMaDRzyYNwrMLy2/biLEwJAJbqBKto4ISA3RbhfxA57GvhfCis5\nl3f9D8YL6a09xI3+yiB/Bo3f/T/mlTOFpULeJ9zqB6ebZlOMYnyHO6Z3+wJBALKj\nSkJF3XIrz2XDpgdUPBlOlXhjAVbz+4v8B8rDtwJZnv4fTJNyuSr4w7tJPaCGM3Cw\nMaaPTWYZrk8xfXCYYKUCQQCMewBZiEeAQ+wNv7Zk/NqPaRYbJNGgzuo+ixb/vPZ1\nR6RfK881pTifCVHGTr6IK2qdXnDLWi4YFMRe3sTktA4E\n-----END RSA PRIVATE KEY-----\n"
  graceful:
    maxSecond: 5s  

auth:
  jwtToken:
    type: token
    expired: 3m
    refreshExpired: 15m

database:
  mysql:
    user: root
    password: a5k4CooL
    host: localhost
    port: 3306
    name: play-db
    maxIdleConns: 5
    maxOpenConns: 20
    connMaxLifetime: 60
    connMaxIdleTime: 10
  postgres:
    user: root
    password: a5k4CooL
    host: localhost
    port: 5432
    name: postgres

cache:
  redis:
    host: localhost
    port: 6379
    password:

module:
  news:
    scheduler:
      getNewsRSSEnable: false
      getNewsRSSDuration: 180 # in seconds
      getNewsIndexEnable: true
      getNewsIndexDuration: 10 # in seconds
    service:
      urlNewsRSS: https://jambi.antaranews.com/rss/terkini.xml
      urlNewsIndex: https://www.bisnis.com/index
    