package router

import (
	"github.com/go-chi/chi/v5"
	"github.com/go-chi/cors"
	httpswagger "github.com/swaggo/http-swagger"

	"github.com/linggaaskaedo/go-playground-wire-v3/src/handler/rest"
)

type HttpRouterImpl struct {
	restHandler *rest.RestHandlerImpl
}

func NewHttpRouter(
	restHandler *rest.RestHandlerImpl,
) *HttpRouterImpl {
	return &HttpRouterImpl{
		restHandler: restHandler,
	}
}

// setup cors
func (h *HttpRouterImpl) cors(r *chi.Mux) {
	r.Use(cors.AllowAll().Handler)
}

func (h *HttpRouterImpl) Router(r *chi.Mux) {
	h.cors(r)
	h.restHandler.Router(r)

	// Setup swagger docs from autogenerated swagger
	r.Mount("/swagger", httpswagger.WrapHandler)
}
